spring:
  application:
    name: card_nav
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT:3306}/${DB_NAME:card_nav}?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.tao.card_nav.entity
  configuration:
    map-underscore-to-camel-case: true

server.port: ${SERVER_PORT:3002}

spring.jackson.date-format: yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone: GMT+8

spring.servlet.multipart.max-file-size: 10MB
spring.servlet.multipart.max-request-size: 10MB


langchain4j:
  open-ai:
    chat-model:
      base-url: ${API_URL}
      api-key: ${API_KEY}
      model-name: ${MODEL_NAME}
      log-requests: true
      log-responses: true
      max-token: 200000
      temperature: 0.5
    streaming-chat-model:
      base-url: ${API_URL}
      api-key: ${API_KEY}
      model-name: ${MODEL_NAME}
      log-requests: true
      log-responses: false
      max-token: 200000
      temperature: 0.3




